stukbook/config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {registrations: 'registrations'}

   root 'pages#home'
   resources :users, only: [:show, :index]
   resources :friendships, only: [:create, :destroy, :accept] do
    member do
      put :accept
    end
  end

  resources :posts, only: [:create, :edit, :update, :destroy]

end

stukbook/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :username
  validates_uniqueness_of :username

  has_many :friendships, dependent: :destroy
  has_many :inverse_friendships, class_name: "Friendship", foreign_key: "friend_id", dependent: :destroy
  has_many :posts, dependent: :destroy

  def request_friendship(user_2)
  	self.friendships.create(friend: user_2)
  end

  def pending_friend_requests_from
  	self.inverse_friendships.where(state: "pending")
  end

  def pending_friend_requests_to
  	self.friendships.where(state: "pending")
  end


  def active_friends
  	self.friendships.where(state: "active").map(&:friend) + self.inverse_friendships.where(state: "active").map(&:user)
  end

  def friendship_status(user_2)
  	friendship = Friendship.where(user_id: [self.id,user_2.id], friend_id: [self.id,user_2.id])
  	unless friendship.any?
  		return "not friends"
  	else
      if friendship.first.state == "active"
        return "friends"
      else
        if friendship.first.user == self
          return "pending"
        else
          return "requested"
        end
      end
    end
  end
  
  def friendship_relation(user_2)
    Friendship.where(user_id: [self.id,user_2.id], friend_id: [self.id,user_2.id]).first
  end

end

stukbook/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

stukbook/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

stukbook/app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

	private
	
	def sign_up_params
		params.require(:user).permit(:email, :password, :password_confirmation, :username)
	end

	def account_update_params
		params.require(:user).permit(:email, :password, :password_confirmation, :username, :current_password, :current_password, :age, :bio, :gender)
	end
end

stukbook/app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!, only:[:index]
	before_action :set_user, only:[:show]

	def index
		case params[:people] when "friends"
			@users = current_user.active_friends
		when "requests"
			@users = current_user.pending_friend_requests_from.map(&:user)
		when "pending"
			@users = current_user.pending_friend_requests_to.map(&:friend)
		else
			@users = User.where.not(id: current_user.id)
		end
	end

  	def show
  		@post = Post.new
  		@posts = @user.posts.order('created_at DESC')
  		@activities = PublicActivity::Activity.where(owner_id: @user.id).order('created_at DESC')
  	end

	  private
	  	def set_user
	  		@user = User.find_by(username: params[:id])
	  	end
end

stukbook/app/helpers/application_helper.rb
module ApplicationHelper
end

stukbook/app/helpers/pages_helper.rb
module PagesHelper
end

stukbook/app/helpers/users_helper.rb
module UsersHelper

	def action_buttons(user)
		case current_user.friendship_status(user) when "friends"
			link_to "Cancel friendship", friendship_path(current_user.friendship_relation(user)), method: :delete
			when "pending"
			link_to "Cancel request", friendship_path(current_user.friendship_relation(user)), method: :delete
			when "requested"
			link_to "Accept request", accept_friendship_path(current_user.friendship_relation(user)), method: :put
			when "not friends"
		  link_to "Add as friend", friendships_path(user_id: user.id), method: :post
		end
	end

end

stukbook/app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Stukbook", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        
        
        
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Timeline</a></li>
        <% if current_user %>
        <li><%= link_to "People", users_path %></li>
        <% end %>
        <% if current_user %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= gravatar_tag current_user.email, size: 20 %><%= current_user.username %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Profile", user_path(current_user.username) %></li>
            <li><a href="#">Friends</a></li>
            <li><a href="#"><%= link_to "Settings", edit_user_registration_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %> </li>
          </ul>
        </li>
        <% else %>
        <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

stukbook/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stukbook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render "layouts/header" %>
<% flash.each do |type, message| %>
  <div class="alert alert-info fade-in">
    <button class="close" data-dismiss="alert">x</button>
    <%= message %>
  </div>
<% end %>
<%= yield %>

</body>
</html>

stukbook/app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

stukbook/app/views/users/show.html.erb
<div class="jumbtron">
	<div class="container">

		<div class="row">

			<div class="col-md-4">
				<%= gravatar_tag @user.email, size: 200 %>
			</div>

			<div class="col-md-4">
				<h3><%= @user.username %></h3>
				<p>Age: <%= @user.age %></p>
				<p>Gender: <%= @user.gender %></p>
			</div>	

			<div class="col-md-4">
				<h3>Who am I</h3>
				<small><%= @user.bio %></small>
			</div>		

		</div>

	</div>
</div>

<div class="container">
	<div class="row">
		<!-- Friend Zone -->
		<div class="col-md-3">
			<div class="panel panel-default">
				<div class="panel-heading">Friends (<%= @user.active_friends.size %>) </div>
				<div class="panel-body">
					<%= @user.active_friends.last(16).each do |user| %>
					<%= link_to user_path(user.username) do %>
					<%= gravatar_tag user.email, size: 40 %>
					<% end %>
					<% end %>
				</div>
			</div>
		</div>
		<!-- Post Zone -->
		<div class="col-md-6">
			<%= render 'posts/form' %>
			<%= render @posts %>
		</div>
		<!-- Profile Activity -->
		<div class="col-md-3">
			<div class="panel panel-default">
				<div class="panel-heading">Recent Activity </div>
				<div class="panel-body">
					<%= render_activities(@activities) %>
				</div>
			</div>
		</div>
	</div>

</div>